// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com.checkout.data;

#nullable disable

namespace com.checkout.data.Migrations
{
    [DbContext(typeof(CKODBContext))]
    [Migration("20220605081510_CKOV9")]
    partial class CKOV9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("com.checkout.data.Model.CardDetails", b =>
                {
                    b.Property<int>("CardDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardDetailsID"), 1L, 1);

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardDetailsID");

                    b.ToTable("Cards", (string)null);

                    b.HasData(
                        new
                        {
                            CardDetailsID = 1,
                            CardNumber = "123456789",
                            Cvv = "111",
                            ExpiryMonth = "11",
                            ExpiryYear = "2024",
                            HolderName = "Valid Card"
                        });
                });

            modelBuilder.Entity("com.checkout.data.Model.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyCode = "QAR",
                            CurrencyName = "Qatari Riyal"
                        },
                        new
                        {
                            Id = 2,
                            CurrencyCode = "USD",
                            CurrencyName = "US Dollar"
                        },
                        new
                        {
                            Id = 3,
                            CurrencyCode = "GBP",
                            CurrencyName = "British Pound"
                        });
                });

            modelBuilder.Entity("com.checkout.data.Model.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Merchants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c4352e9-beb6-4c7f-8bfc-9263de60238b"),
                            Country = "USA",
                            Name = "Github"
                        },
                        new
                        {
                            Id = new Guid("836cc81c-66b7-444f-9860-850f3bcc4b88"),
                            Country = "USA",
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = new Guid("3205a75c-259b-48a4-9eed-5bdce3c7ff18"),
                            Country = "UK",
                            Name = "Farfetch"
                        });
                });

            modelBuilder.Entity("com.checkout.data.Model.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CardDetailsID")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyID")
                        .HasColumnType("int");

                    b.Property<Guid>("MerchantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("CardDetailsID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("MerchantID");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionID = new Guid("ed9a5b76-b5cc-46f6-9372-7657a2812158"),
                            Amount = 322m,
                            CardDetailsID = 1,
                            CurrencyID = 1,
                            MerchantID = new Guid("1c4352e9-beb6-4c7f-8bfc-9263de60238b"),
                            Status = "Created",
                            StatusCode = "C_00001"
                        });
                });

            modelBuilder.Entity("com.checkout.data.Model.Transaction", b =>
                {
                    b.HasOne("com.checkout.data.Model.CardDetails", "CardDetails")
                        .WithMany()
                        .HasForeignKey("CardDetailsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.checkout.data.Model.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.checkout.data.Model.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardDetails");

                    b.Navigation("Currency");

                    b.Navigation("Merchant");
                });
#pragma warning restore 612, 618
        }
    }
}
